return {
	"nvim-telescope/telescope.nvim",
	version = "*",
	dependencies = { 'nvim-lua/plenary.nvim' },
	cmd = "Telescope",
	keys = {
		{
			"<leader>,",
			"<cmd>Telescope buffers sort_mru=true sort_lastused=true theme=ivy <cr>",
			desc = "Switch Buffer",
		},
		{ "<leader>/",        "<cmd>Telescope live_grep theme=ivy <cr>",                                desc = "Grep" },
		{ "<leader>:",        "<cmd>Telescope command_history theme=ivy <cr>",                          desc = "Command History" },
		-- find
		{ "<leader>fb",       "<cmd>Telescope buffers sort_mru=true sort_lastused=true theme=ivy <cr>", desc = "Buffers" },
		{ "<leader>ff",       "<cmd>Telescope find_files theme=ivy <cr>",                               desc = "Find Files" },
		{ "<leader>fr",       "<cmd>Telescope oldfiles theme=ivy <cr>",                                 desc = "Recent" },
		{ "<leader><leader>", "<cmd>Telescope git_files theme=ivy <cr>",                                desc = "Recent" },
		-- git
		{ "<leader>gc",       "<cmd>Telescope git_commits theme=ivy <cr>",                              desc = "commits" },
		{ "<leader>gs",       "<cmd>Telescope git_status theme=ivy <cr>",                               desc = "status" },
		-- search
		{ '<leader>s"',       "<cmd>Telescope registers theme=ivy <cr>",                                desc = "Registers" },
		{ "<leader>sa",       "<cmd>Telescope autocommands theme=ivy <cr>",                             desc = "Auto Commands" },
		{ "<leader>sb",       "<cmd>Telescope current_buffer_fuzzy_find theme=ivy <cr>",                desc = "Buffer" },
		{ "<leader>sc",       "<cmd>Telescope command_history theme=ivy <cr>",                          desc = "Command History" },
		{ "<leader>sC",       "<cmd>Telescope commands theme=ivy <cr>",                                 desc = "Commands" },
		{ "<leader>sd",       "<cmd>Telescope diagnostics bufnr=0 theme=ivy <cr>",                      desc = "Document diagnostics" },
		{ "<leader>sD",       "<cmd>Telescope diagnostics theme=ivy <cr>",                              desc = "Workspace diagnostics" },
		{ "<leader>sg",       "<cmd>Telescope live_grep theme=ivy <cr>",                                desc = "Grep (root dir)" },
		{ "<leader>sh",       "<cmd>Telescope help_tags theme=ivy <cr>",                                desc = "Help Pages" },
		{ "<leader>sH",       "<cmd>Telescope highlights theme=ivy <cr>",                               desc = "Search Highlight Groups" },
		{ "<leader>sk",       "<cmd>Telescope keymaps theme=ivy <cr>",                                  desc = "Key Maps" },
		{ "<leader>sM",       "<cmd>Telescope man_pages theme=ivy <cr>",                                desc = "Man Pages" },
		{ "<leader>sm",       "<cmd>Telescope marks theme=ivy <cr>",                                    desc = "Jump to Mark" },
		{ "<leader>so",       "<cmd>Telescope vim_options theme=ivy <cr>",                              desc = "Options" },
		{ "<leader>sR",       "<cmd>Telescope resume theme=ivy <cr>",                                   desc = "Resume" },
		{ "<leader>ss",       "<cmd>Telescope lsp_document_symbols theme=ivy <cr>",                     desc = "Goto Symbol", },
		{ "<leader>sS",       "<cmd>Telescope lsp_dynamic_workspace_symbols theme=ivy <cr>",            desc = "Goto Symbol (Workspace)", },
	},
	opts = {
		defaults = {
			vimgrep_arguments = {
				"rg",
				"-L",
				"--color=never",
				"--no-heading",
				"--with-filename",
				"--line-number",
				"--column",
				"--smart-case",
			},
			prompt_prefix = "   ",
			selection_caret = "  ",
			entry_prefix = "  ",
			initial_mode = "insert",
			selection_strategy = "reset",
			sorting_strategy = "ascending",
			layout_strategy = "horizontal",
			layout_config = {
				horizontal = {
					prompt_position = "top",
					preview_width = 0.55,
					results_width = 0.8,
				},
				vertical = {
					mirror = false,
				},
				width = 0.87,
				height = 0.80,
				-- preview_cutoff = 120,
			},
			file_ignore_patterns = { "node_modules" },
			path_display = { "truncate" },
			winblend = 0,
			border = {},
			borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
			color_devicons = true,
			set_env = { ["COLORTERM"] = "truecolor" }, -- default = nil,
			file_sorter = require("telescope.sorters").get_fuzzy_file,
			generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
			file_previewer = require("telescope.previewers").vim_buffer_cat.new,
			grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
			qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
		},

		extensions_list = { "themes", "terms" },
		extensions = {
			fzf = {
				fuzzy = true,
				override_generic_sorter = true,
				override_file_sorter = true,
				case_mode = "smart_case",
			},
		},
	}
}
