theme = "rose_pine_moon_transparent"

[editor]
# line-number = "relative"
auto-format = true
auto-save = true
true-color = true
auto-completion = true
idle-timeout = 1
bufferline = "multiple"
cursorcolumn = true
cursorline = true
color-modes = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'
'|' = '|'

[editor.soft-wrap]
enable = true
max-wrap = 25

[editor.indent-guides]
render = true
#character = "|"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.file-picker]
hidden = false

[keys.normal]
H = "goto_previous_buffer"
L = "goto_next_buffer"
V = ["goto_first_nonwhitespace", "extend_to_line_end", "select_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
x = "extend_line"
C-d = ["half_page_down", "align_view_center"]
C-u = ["half_page_up", "align_view_center"]
C-e ="scroll_down"
C-y = "scroll_up"
C-s = ":w"
C-j = "save_selection"
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]


[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
x = ":bc"
l = ":toggle lsp.display-inlay-hints"
c = ":format"

[keys.insert]
j = { j = "normal_mode" } # Maps `jj` to exit insert mode
C-s = ":w"
C-h = "move_char_left"
C-l = "move_char_right"
C-j = "move_line_down"
C-k = "move_line_up"

