complete -c nh -n "__fish_use_subcommand" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c nh -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c nh -n "__fish_use_subcommand" -f -a "os" -d 'NixOS functionality'
complete -c nh -n "__fish_use_subcommand" -f -a "home" -d 'Home-manager functionality'
complete -c nh -n "__fish_use_subcommand" -f -a "search" -d 'Searches packages by querying search.nixos.org'
complete -c nh -n "__fish_use_subcommand" -f -a "clean" -d 'Enhanced nix cleanup'
complete -c nh -n "__fish_use_subcommand" -f -a "completions" -d 'Generate shell completion files into stdout'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "switch" -d 'Build and activate the new configuration, and make it the boot default'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "boot" -d 'Build the new configuration and make it the boot default'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "test" -d 'Build and activate the new configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "build" -d 'Build the new configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from boot; and not __fish_seen_subcommand_from test; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "info" -d 'Show an overview of the system\'s info'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s H -l hostname -d 'Output to choose from the flakeref. Hostname is used by default' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s s -l specialisation -d 'Name of the specialisation' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s S -l no-specialisation -d 'Don\'t use specialisations'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from switch" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s H -l hostname -d 'Output to choose from the flakeref. Hostname is used by default' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s s -l specialisation -d 'Name of the specialisation' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s S -l no-specialisation -d 'Don\'t use specialisations'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from boot" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s H -l hostname -d 'Output to choose from the flakeref. Hostname is used by default' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s s -l specialisation -d 'Name of the specialisation' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s S -l no-specialisation -d 'Don\'t use specialisations'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from test" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s H -l hostname -d 'Output to choose from the flakeref. Hostname is used by default' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s s -l specialisation -d 'Name of the specialisation' -r
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s S -l no-specialisation -d 'Don\'t use specialisations'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from info" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from os; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from home; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from home; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from home; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "switch" -d 'Build and activate a home-manager configuration'
complete -c nh -n "__fish_seen_subcommand_from home; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "build" -d 'Build a home-manager configuration'
complete -c nh -n "__fish_seen_subcommand_from home; and not __fish_seen_subcommand_from switch; and not __fish_seen_subcommand_from build; and not __fish_seen_subcommand_from info" -f -a "info" -d 'Show an overview of the installation'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s c -l configuration -d 'Name of the flake homeConfigurations attribute, like username@hostname' -r
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s b -l backup-extension -d 'Move existing files by backing up with the extension' -r
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from switch" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s c -l configuration -d 'Name of the flake homeConfigurations attribute, like username@hostname' -r
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s b -l backup-extension -d 'Move existing files by backing up with the extension' -r
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s a -l ask -d 'Ask for confirmation'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s u -l update -d 'Update flake inputs before building specified configuration'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -l no-nom -d 'Don\'t use nix-output-monitor for the build process'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from info" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from home; and __fish_seen_subcommand_from info" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from search" -s l -l limit -d 'Number of search results to display' -r
complete -c nh -n "__fish_seen_subcommand_from search" -s c -l channel -d 'Name of the channel to query (e.g nixos-23.11, nixos-unstable)' -r
complete -c nh -n "__fish_seen_subcommand_from search" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from user; and not __fish_seen_subcommand_from profile" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from user; and not __fish_seen_subcommand_from profile" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from user; and not __fish_seen_subcommand_from profile" -f -a "all" -d 'Cleans root profiles and calls a store gc'
complete -c nh -n "__fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from user; and not __fish_seen_subcommand_from profile" -f -a "user" -d 'Cleans the current user\'s profiles and calls a store gc'
complete -c nh -n "__fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from all; and not __fish_seen_subcommand_from user; and not __fish_seen_subcommand_from profile" -f -a "profile" -d 'Cleans a specific profile'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s k -l keep -d 'At least keep this number of generations' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s K -l keep-since -d 'At least keep gcroots and generations in this time range since now' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s a -l ask -d 'Ask for confimation'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -l nogc -d 'Don\'t run nix store --gc'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -l nogcroots -d 'Don\'t clean gcroots'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from all" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s k -l keep -d 'At least keep this number of generations' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s K -l keep-since -d 'At least keep gcroots and generations in this time range since now' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s a -l ask -d 'Ask for confimation'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -l nogc -d 'Don\'t run nix store --gc'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -l nogcroots -d 'Don\'t clean gcroots'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from user" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s k -l keep -d 'At least keep this number of generations' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s K -l keep-since -d 'At least keep gcroots and generations in this time range since now' -r
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s n -l dry -d 'Only print actions, without performing them'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s a -l ask -d 'Ask for confimation'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -l nogc -d 'Don\'t run nix store --gc'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -l nogcroots -d 'Don\'t clean gcroots'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from clean; and __fish_seen_subcommand_from profile" -s h -l help -d 'Print help'
complete -c nh -n "__fish_seen_subcommand_from completions" -s s -l shell -d 'Name of the shell' -r -f -a "{bash	'',elvish	'',fish	'',powershell	'',zsh	''}"
complete -c nh -n "__fish_seen_subcommand_from completions" -s v -l verbose -d 'Show debug logs'
complete -c nh -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help'
