[user]
name = "Akira"
email = "44054643+KSaiAkshit@users.noreply.github.com"

[ui]
default-command = "log"
diff.format = "git"
diff.tool = ["difft", "--color=always", "--display=side-by-side-show-both", "$left", "$right"]
diff-editor = ":builtin"

[template-aliases]
'format_short_signature(signature)' = 'signature.name()'

[snapshot]
max-new-file-size = "32MiB"

[aliases]
ss = ["show", "--summary"]
l = ["log", "-r", "all()"]
