-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("VimEnter", {
--   callback = function()
--     local bufferPath = vim.fn.expand("%:p")
--     if vim.fn.isdirectory(bufferPath) ~= 0 then
--       local ts_builtin = require("telescope.builtin")
--       -- vim.api.nvim_buf_delete(0, { force = true })
--       ts_builtin.find_files()
--     end
--   end,
-- })
vim.cmd("highlight GitSignsAdd guibg=NONE")
