#!/bin/bash

image_dir="$HOME/Pictures/"
random_image=$(find "$image_dir" -type f -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" | shuf -n 1)

if [[ -n $random_image ]]; then
	swww img "$random_image"
else
	notify-send --urgency=critical 'No image found'
fi
