import = ["/home/akira/.config/alacritty/rose-pine.toml"]
# import = ["/home/akira/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_timeout = 10

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
# family = "Iosevka Nerd Font"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
action = "Hide"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zellij"
args = ["-l", "welcome"]
# args = ["a", "-c"]

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.6

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
